// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqwosaofjeynkdjzjqhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impxd29zYW9mamV5bmtkanpqcWhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MzM0MDUsImV4cCI6MjA2MDIwOTQwNX0.pWNaHc7n54a87dDFSgIOQluEsGThFBp8X3cMHZ-6Nvw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);